# Generated by Django 5.0.6 on 2024-07-16 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
            preserve_default=False,
        ),
    ]
