# Generated by Django 5.0.6 on 2024-07-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_productagent_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(default='python', max_length=128),
        ),
    ]
