# Generated by Django 5.0.6 on 2024-07-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_code_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='name',
            field=models.CharField(default='example.py', max_length=128),
        ),
    ]
